version: '3.8'

services:
  job-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - job_data:/var/lib/postgresql/data
    networks:
      - job-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - job-network

  job-runner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2112:2112"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
    depends_on:
      - job-db
    networks:
      - job-network

volumes:
  job_data:

networks:
  job-network:
    driver: bridge
