version: '3.8'

services:
  job-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - job_data:/var/lib/postgresql/data
    networks:
      - job-network

volumes:
  job_data:
  redis_data:

networks:
  job-network:
    driver: bridge
